/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include "MyStm32f407xx.h"
#define BTN_PRESSED ENABLE

void algofun();
//void unlock_door(void);
//void alarm_activation_deactivation (void);
int x=0;
int res;
void delay(void)
{
	for(uint32_t i=0;i<500000/10; i++);
}
int main(void)
{
    GPIO_Handle_t GPioLed,GPIOBtn;

    GPioLed.pGPIOx = GPIOD;
    GPioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
    GPioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    GPioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GPioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    GPioLed.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN;
    GPIO_PeriClockControl(GPIOD, ENABLE);
    GPIO_Init(&GPioLed);

    GPioLed.pGPIOx = GPIOD;
        GPioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
        GPioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
        GPioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
        GPioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
        GPioLed.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN;
        GPIO_PeriClockControl(GPIOD, ENABLE);
        GPIO_Init(&GPioLed);

        GPioLed.pGPIOx = GPIOD;
            GPioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
            GPioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
            GPioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
            GPioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
            GPioLed.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN;
            GPIO_PeriClockControl(GPIOD, ENABLE);
            GPIO_Init(&GPioLed);

            GPioLed.pGPIOx = GPIOD;
                GPioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
                GPioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
                GPioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
                GPioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
                GPioLed.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN;
                GPIO_PeriClockControl(GPIOD, ENABLE);
                GPIO_Init(&GPioLed);

    GPIOBtn.pGPIOx = GPIOA;
    GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
    GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
    GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIOBtn.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN;
    GPIO_PeriClockControl(GPIOA, ENABLE);
        GPIO_Init(&GPIOBtn);



    	//if(x==5)
    	//{
    		//door will unlock;
    	//}
    	//else
    	//{
    		//lock;
    	//}


    	if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == BTN_PRESSED)
    	{
    		//delay();
    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, 1);
    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, 1);
    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, 1);
    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, 1);

    	}




    		    	    	if((GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == BTN_PRESSED) && (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == BTN_PRESSED))
    		    	    		    		    	    	{
    		    	    			//delay();

    		    	    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_12, 0);
    		    	    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_13, 0);
    		    	    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_14, 0);
    		    	    		    GPIO_WriteToOutputPin(GPIOD, GPIO_PIN_NO_15, 0);



    		    	    	}






}
